<h1>Nouvel utilisateur</h1>
<form action="" method="post" novalidate>
	<div>
		<input type="text" name="firstname" placeholder="Nom">
	</div>

	<div>
		<input type="text" name="lastname" placeholder="Prénom">
	</div>

    <div>
		<input type="phone" name="telephone" placeholder="phone">
	</div>

	<div>
		<input type="email" name="email" placeholder="Email">
	</div>

	<div>
		<input type="address" name="adresse" placeholder="address">
	</div>


	<div>
		<select name="role">
			<option value="1">annonceur</option>
			<option value="2">client</option>
		</select>
	</div>

	<div>
		<input type="submit" value="Ajouter">
	</div>
</form>